### ISSUE TITLE
Branch : quicklogic : Issue while loading the edf file on spde "$_dlatch_p_.edi' "

### ISSUE THREAD

**Issue by kkumar23** [SymbiFlow/yosys#60]
## Steps to reproduce the issue
Synthesize the attached design with yosys for the quicklogic.
Now load the edf onto spde tool, Spde throws the below error:

Error    : nm_1007: Library 'C:\QuickLogic\QuickWorks_2016.2_Release\spde\data\PolarPro-III\edif\$_dlatch_p_.edi'  is not supported for this family

It looks like the library of yosys is missing the dlatch [implementation.](url
[rtl.zip](https://github.com/SymbiFlow/yosys/files/4298296/rtl.zip)

[uart_yosys.zip](https://github.com/SymbiFlow/yosys/files/4298299/uart_yosys.zip)
[uart_spde.zip](https://github.com/SymbiFlow/yosys/files/4298302/uart_spde.zip)

)

**Comment by kkumar23** [comment]
Any update on this issue?

**Comment by glatosinski** [comment]
We've added support for latches for Quicklogic branch. However, the designs you've introduced won't work, since there is no inout support in Yosys for Quicklogic. We're working on inout support in Yosys now.

**Comment by glatosinski** [comment]
The support for inout in Quicklogic's script in Yosys is added. Your design should now be parsed correctly by SpDE.

**Comment by kkumar23** [comment]
Hi Glatosinski, 
   I used the latest branch https://github.com/antmicro/yosys.git -b quicklogic quicklogic-yosys. to compile the Yosys. and updated the script "pip3 install git+https://github.com/antmicro/yosys-SpDE-flow.git" , i still get the same latch error in spde.

<blockquote><img src="https://avatars3.githubusercontent.com/u/927785?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/antmicro/yosys">antmicro/yosys</a></strong></div><div>Yosys Open SYnthesis Suite. Contribute to antmicro/yosys development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/927785?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/antmicro/yosys-SpDE-flow">antmicro/yosys-SpDE-flow</a></strong></div><div>Contribute to antmicro/yosys-SpDE-flow development by creating an account on GitHub.</div></blockquote>

**Comment by glatosinski** [comment]
The branch was updated yesterday's afternoon, sorry for the delay. Please check if it works for you. I've downloaded now the latest version of Yosys from https://github.com/antmicro/yosys.git (quicklogic branch) and it worked with SpDE.

<blockquote><img src="https://avatars3.githubusercontent.com/u/927785?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/antmicro/yosys">antmicro/yosys</a></strong></div><div>Yosys Open SYnthesis Suite. Contribute to antmicro/yosys development by creating an account on GitHub.</div></blockquote>

**Comment by kkumar23** [comment]
Thank you, I am able to run now.
