### ISSUE TITLE
Branch : Quicklogic : In symbiflow ''ram8k_2x1_cell_macro'' not supported

### ISSUE THREAD

**Issue by rakeshm75** [SymbiFlow/yosys#69]
When run the attached design through the symbiflow, we get the following error:

Error 1: 
Type: Blif file
File: /home/rakeshm/symbiflow-arch-defs/build/quicklogic/tests/quicklogic_testsuite/design1/design1-ql-chandalar/ql-s3-ql-eos-s3-virt-ql-eos-s3-wlcsp/top.eblif
Line: 11551
Message: Failed to find matching architecture model for 'ram8k_2x1_cell_macro'
[rtl1.zip](https://github.com/SymbiFlow/yosys/files/4422383/rtl1.zip)

**Comment by kgugala** [comment]
this should be fixed now. Please fetch the latest code and run the tests again. There is also a RAM test included in the repository https://github.com/antmicro/symbiflow-arch-defs/tree/quicklogic-upstream-rebase/quicklogic/tests/ram 

<blockquote><img src="https://avatars3.githubusercontent.com/u/927785?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/antmicro/symbiflow-arch-defs">antmicro/symbiflow-arch-defs</a></strong></div><div>FOSS architecture definitions of FPGA hardware useful for doing PnR device generation. - antmicro/symbiflow-arch-defs</div></blockquote>

**Comment by rakeshm75** [comment]
This issue is fixed, so closing the issue.
